clc;
clear all;
close all;
warning off;
rec=audiorecorder;
recordblocking(rec,5);
x=getaudiodata(rec);
Fs=8000;
t=(0:(length(x)-1))/Fs;
subplot(2,1,1);
plot(x);
xlabel('Time');
ylabel('Magnitude');
title('Original Signal');
X=fftshift(fft(x));
subplot(2,1,2);
plot(abs(X));
xlabel('Frequency');
ylabel('Magnitude');
title('Double- Sided Magnitude Spectrum');